name: Update Manifest Automatically

on:
  schedule:
    - cron: "0 * * * *"   # Runs every hour
  workflow_dispatch:       # Allows manual trigger from the Actions tab

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # ensures the workflow can push commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest manifest.json (with debug info)
        run: |
          echo "Fetching manifest from server..."
          curl -v http://24.220.43.81:60421/manifest.json -o manifest.json || exit 1
          echo ""
          echo "===== FILE CONTENTS ====="
          cat manifest.json || echo "No manifest file downloaded."
          echo "========================="

      - name: Commit and push if updated
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          # Show current git status
          git status

          # Stage and commit if changed
          git add manifest.json || exit 1
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update manifest.json"
            git push
          fi
