name: Update Manifest Automatically

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:      # Allows manual trigger from GitHub Actions tab

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest manifest.json
        run: curl -s http://24.220.43.81:60421/manifest.json -o manifest.json

      - name: Commit and push changes if updated
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          if ! git diff --quiet manifest.json; then
            git add manifest.json
            git commit -m "Auto-update manifest.json"
            git push
          else
            echo "No changes to commit"
          fi
